<a href="https://colab.research.google.com/github/Jahan08/Amber-tutorial/blob/main/hERG-web-app-part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [411]:
import pandas as pd

In [412]:
df = pd.read_csv('/content/bioactivity_data_hERG_activity_pubchem_First.csv')

In [413]:
df_Y = df['Activity']
df_Y
Y = df_Y

In [415]:
df_X = df.drop(columns=['Name'])
df_X = df_X.drop(columns=['Activity'])
df_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2320,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2321,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2322,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2323,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

### Remove low variance features

In [416]:
from sklearn.feature_selection import VarianceThreshold

def remove_low_variance(input_data, threshold=0.1):
    selection = VarianceThreshold(threshold)
    selection.fit(input_data)
    return input_data[input_data.columns[selection.get_support(indices=True)]]

df_X = remove_low_variance(df_X, threshold=0.1)
df_X

,PubchemFP3,PubchemFP16,PubchemFP19,PubchemFP20,PubchemFP23,PubchemFP24,PubchemFP33,PubchemFP37,PubchemFP143,PubchemFP145,...,PubchemFP758,PubchemFP776,PubchemFP777,PubchemFP779,PubchemFP797,PubchemFP798,PubchemFP800,PubchemFP818,PubchemFP819,PubchemFP821
0,0,0,1,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,1,0,0,1,1,1,...,1,0,0,0,0,0,0,0,0,1
2,1,0,1,1,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
3,0,0,0,0,1,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
4,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319,0,0,1,1,1,1,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
2320,1,1,1,1,0,0,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
2321,0,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2322,1,0,1,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2323,1,0,1,0,0,0,0,0,1,1,...,1,1,0,0,0,0,1,0,0,1

In [417]:
df_X.shape

(2324, 239)

In [ ]:
#from sklearn.neural_network import MLPClassifier
#from sklearn.datasets import make_classification
#from sklearn.model_selection import train_test_split

#X, Y = make_classification(random_state=100)
#X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

In [ ]:
#model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(10, 2))
#model.fit(X_train, Y_train)
#r2 = model.score(X_test, Y_test)
#r2

0.8

## Logistic Regression 

Simple neural network: https://theopetunde.medium.com/a-step-by-step-tutorial-on-coding-neural-network-logistic-regression-model-from-scratch-5f9025bd3d6

In [418]:
X = df_X

In [419]:
from sklearn import preprocessing
import numpy as np
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
scaler = preprocessing.StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
X_scaled

array([[ 2.10473432, -1.10855774,  0.75609933, ..., -0.45504254,
        -0.3741133 ,  1.98084043],
       [-0.47511935,  0.902073  ,  0.75609933, ...,  2.19759674,
        -0.3741133 , -0.50483622],
       [-0.47511935,  0.902073  ,  0.75609933, ..., -0.45504254,
        -0.3741133 , -0.50483622],
       ...,
       [-0.47511935,  0.902073  , -1.32257754, ...,  2.19759674,
        -0.3741133 , -0.50483622],
       [-0.47511935, -1.10855774, -1.32257754, ..., -0.45504254,
        -0.3741133 , -0.50483622],
       [-0.47511935,  0.902073  ,  0.75609933, ..., -0.45504254,
        -0.3741133 , -0.50483622]])

In [420]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

X, Y = make_classification(random_state=100)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, Y_train)  # apply scaling on training data

pipe.score(X_test, Y_test)

0.76

## Save model as pickle object

In [421]:
import pickle

In [422]:
pickle.dump(pipe, open('hERG_model.pkl', 'wb'))