<a href="https://colab.research.google.com/github/Jahan08/Amber-tutorial/blob/main/Retrieve-Data-Cell-line-TB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install chembl_webresource_client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.8-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 KB 1.5 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (1.26.15)
Requirement already satisfied: easydict in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (1.10)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (2.25.1)
Collecting requests-cache~=0.7.0
  Downloading requests_cache-0.7.5-py3-none-any.whl (39 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.10)
Collecting url-normalize<2.0,>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: itsdangerous>=2.0.1 in /usr/local/lib/python3.9/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (2.1.2)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.9/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (6.0)
Collecting attrs<22.0,>=21.2
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 1.9 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.15.0)
Installing collected packages: url-normalize, attrs, requests-cache, chembl_webresource_client
  Attempting uninstall: attrs
    Found existing installation: attrs 22.2.0
    Uninstalling attrs-22.2.0:
      Successfully uninstalled attrs-22.2.0
Successfully installed attrs-21.4.0 chembl_webresource_client-0.10.8 requests-cache-0.7.5 url-normalize-1.4.3

In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [3]:
target = new_client.target
target_query = target.search('A549')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,A549,19.0,False,CHEMBL392,[],CELL-LINE,9606
1,[],Homo sapiens,A549/CDDP,16.0,False,CHEMBL4483225,[],CELL-LINE,9606
2,[],Homo sapiens,A549/TR,16.0,False,CHEMBL4483226,[],CELL-LINE,9606

In [4]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL392'

In [5]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [12]:
df = pd.DataFrame.from_dict(res)
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33044,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,4.31
1,None,34302,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,2.02
2,None,36751,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,4.07
3,None,36757,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,3.6
4,None,37932,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42997,None,24517073,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,10.0
42998,None,24517074,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,10.0
42999,None,24517075,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,10.0
43000,None,24517076,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,10.0
43001,None,24517077,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,0.85

In [ ]:
df = pd.read_csv('/content/bioactivity_data_UO-31.csv', header = 0)

<ipython-input-176-0c86e62881e9>:1: DtypeWarning: Columns (15,25,28,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/bioactivity_data_UO-31.csv', header = 0)

In [13]:
# considering nM unit for MIC
#df = df[(df['standard_type'] == 'GI50')]
#df = df[(df['standard_type'] == 'IC50')]
#df = df[(df['standard_type'] == 'EC50')]
df = df[(df['standard_units'] == 'nM')]
df = df[(df['relation'] == '=')]
df = df[df.canonical_smiles.notna()]
df = df[df.standard_value.notna()]
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33044,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,4.31
1,None,34302,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,2.02
2,None,36751,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,4.07
3,None,36757,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,3.6
4,None,37932,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42993,None,24515595,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,3.1
42994,None,24515596,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,3.0
42995,None,24515597,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,2.8
42996,None,24515598,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,2.7
43001,None,24517077,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,A549,9606,None,None,IC50,uM,UO_0000065,None,0.85

In [14]:
fix = []

for i in df.standard_value:
    fix.append(float(i))

STATUS = []

for i in fix:
    if i < 1000:
        STATUS.append("Yes") #active
        
    elif 50000 <= i <= 100000:
        STATUS.append("No") #inactive
        
    else:
        STATUS.append("IN") #intermediate     

df = df.drop('value', 1)
df['value'] = fix
df['Activity'] = STATUS
df

<ipython-input-14-73640f0735c0>:18: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop('value', 1)

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value,Activity
0,None,33044,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,4310.0,IN
1,None,34302,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,2020.0,IN
2,None,36751,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,4070.0,IN
3,None,36757,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,3600.0,IN
4,None,37932,[],CHEMBL621424,In vitro cytotoxicity against human A549 (lung...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,300.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42993,None,24515595,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,3100.0,IN
42994,None,24515596,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,3000.0,IN
42995,None,24515597,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,2800.0,IN
42996,None,24515598,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5057113,Anticancer activity against human A549 cells a...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,2700.0,IN
43001,None,24517077,[],CHEMBL5057666,Cytotoxicity against human A549 cells assessed...,F,None,None,BAO_0000190,BAO_0000219,...,A549,9606,None,None,IC50,uM,UO_0000065,None,850.0,Yes

In [15]:
# considering nM unit for MIC
df = df[(df['Activity'] != 'IN')]
len(df)

8807

In [17]:

df.to_csv('/content/bioactivity_data_TB-cell-line_IC50_new.csv', index=False)