<a href="https://colab.research.google.com/github/Jahan08/Amber-tutorial/blob/main/Retrieve-Data-lung-Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install chembl_webresource_client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.8-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 KB 1.2 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (1.26.15)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (2.25.1)
Collecting requests-cache~=0.7.0
  Downloading requests_cache-0.7.5-py3-none-any.whl (39 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.9/dist-packages (from chembl_webresource_client) (1.10)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2022.12.7)
Requirement already satisfied: itsdangerous>=2.0.1 in /usr/local/lib/python3.9/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (2.1.2)
Collecting attrs<22.0,>=21.2
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 3.6 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.9/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (6.0)
Collecting url-normalize<2.0,>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.15.0)
Installing collected packages: url-normalize, attrs, requests-cache, chembl_webresource_client
  Attempting uninstall: attrs
    Found existing installation: attrs 22.2.0
    Uninstalling attrs-22.2.0:
      Successfully uninstalled attrs-22.2.0
Successfully installed attrs-21.4.0 chembl_webresource_client-0.10.8 requests-cache-0.7.5 url-normalize-1.4.3

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [ ]:
target = new_client.target
target_query = target.search('786-0')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,786-0,32.0,False,CHEMBL613102,[],CELL-LINE,9606.0
1,[],Homo sapiens,Histone H1.0,16.0,False,CHEMBL3707465,"[{'accession': 'P07305', 'component_descriptio...",SINGLE PROTEIN,9606.0
2,[],Homo sapiens,768-0,14.0,False,CHEMBL614043,[],CELL-LINE,9606.0
3,[],None,BL13/0,14.0,False,CHEMBL614704,[],CELL-LINE,NaN
4,[],Homo sapiens,CL1-0,14.0,False,CHEMBL4483232,[],CELL-LINE,9606.0
5,[],Homo sapiens,Neutral amino acid transporter B(0),13.0,False,CHEMBL3562162,"[{'accession': 'Q15758', 'component_descriptio...",SINGLE PROTEIN,9606.0
6,"[{'xref_id': 'Q15466', 'xref_name': None, 'xre...",Homo sapiens,Nuclear receptor subfamily 0 group B member 2,12.0,False,CHEMBL5603,"[{'accession': 'Q15466', 'component_descriptio...",SINGLE PROTEIN,9606.0
7,[],Aspergillus,"1,3-beta-glucan synthase",12.0,True,CHEMBL2364674,"[{'accession': 'Q4WLT4', 'component_descriptio...",SINGLE PROTEIN,5052.0
8,[],Mycobacterium smegmatis,Putative uncharacterized protein atpE,11.0,False,CHEMBL1641346,"[{'accession': 'Q5TIX5', 'component_descriptio...",SINGLE PROTEIN,1772.0
9,"[{'xref_id': 'P51843', 'xref_name': None, 'xre...",Homo sapiens,Nuclear receptor subfamily 0 group B member 1,11.0,False,CHEMBL1795094,"[{'accession': 'P51843', 'component_descriptio...",SINGLE PROTEIN,9606.0
10,[],Bacillus sp.,ATP synthase subunit c,11.0,False,CHEMBL3308989,"[{'accession': 'P00845', 'component_descriptio...",SINGLE PROTEIN,2334.0
11,[],Mycobacterium tuberculosis (strain CDC 1551 / ...,ATP synthase subunit c,11.0,False,CHEMBL4105701,"[{'accession': 'P9WPS0', 'component_descriptio...",SINGLE PROTEIN,83331.0
12,[],Homo sapiens,Sodium- and chloride-dependent neutral and bas...,11.0,False,CHEMBL4680044,"[{'accession': 'Q9UN76', 'component_descriptio...",SINGLE PROTEIN,9606.0
13,[],Bacillus subtilis (strain 168),KinA/Spo0F (sporulation kinase A/sporulation i...,10.0,False,CHEMBL2111331,"[{'accession': 'P06628', 'component_descriptio...",PROTEIN FAMILY,224308.0
14,[],Homo sapiens,Sodium-dependent neutral amino acid transporte...,10.0,False,CHEMBL3351189,"[{'accession': 'Q9H2J7', 'component_descriptio...",SINGLE PROTEIN,9606.0
15,[],Mycobacterium tuberculosis,ATP synthase,8.0,False,CHEMBL2364166,"[{'accession': 'P9WPU9', 'component_descriptio...",PROTEIN COMPLEX,1773.0
16,[],Spinacia oleracea,Chloroplast coupling factor 1,8.0,False,CHEMBL2366567,"[{'accession': 'P00825', 'component_descriptio...",PROTEIN COMPLEX,3562.0

In [ ]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL613102'

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="GI50")

In [ ]:
df = pd.DataFrame.from_dict(res)
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,38564,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,5.88E-7
1,None,43284,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,6.3E-7
2,None,62275,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,4.32E-8
3,None,68744,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,8.43E-7
4,None,138326,[],CHEMBL619279,Tested for cytotoxicity against 786-0 cell lin...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,Log GI50,None,UO_0000065,None,-6.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42698,None,24512320,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,0.49
42699,None,24512321,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.45
42700,None,24512322,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.26
42701,None,24512323,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.77
42702,None,24512324,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,1.49

In [ ]:
df = pd.read_csv('/content/bioactivity_data_UO-31.csv', header = 0)

<ipython-input-176-0c86e62881e9>:1: DtypeWarning: Columns (15,25,28,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/bioactivity_data_UO-31.csv', header = 0)

In [ ]:
# considering nM unit for MIC
#df = df[(df['standard_type'] == 'GI50')]
#df = df[(df['standard_type'] == 'IC50')]
#df = df[(df['standard_type'] == 'EC50')]
df = df[(df['standard_units'] == 'nM')]
df = df[(df['relation'] == '=')]
df = df[df.canonical_smiles.notna()]
df = df[df.standard_value.notna()]
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,38564,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,5.88E-7
1,None,43284,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,6.3E-7
2,None,62275,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,4.32E-8
3,None,68744,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,M,UO_0000065,None,8.43E-7
4,None,138326,[],CHEMBL619279,Tested for cytotoxicity against 786-0 cell lin...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,Log GI50,None,UO_0000065,None,-6.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42698,None,24512320,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,0.49
42699,None,24512321,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.45
42700,None,24512322,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.26
42701,None,24512323,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,2.77
42702,None,24512324,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,Homo sapiens,786-0,9606,None,None,GI50,uM,UO_0000065,None,1.49

In [ ]:
fix = []

for i in df.standard_value:
    fix.append(float(i))

STATUS = []

for i in fix:
    if i < 1000:
        STATUS.append("Yes") #active
        
    elif 20000 <= i <= 100000:
        STATUS.append("No") #inactive
        
    else:
        STATUS.append("IN") #intermediate     

df = df.drop('value', 1)
df['value'] = fix
df['Activity'] = STATUS
df

<ipython-input-14-d453deb383ef>:18: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop('value', 1)

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value,Activity
0,None,38564,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,M,UO_0000065,None,588.00,Yes
1,None,43284,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,M,UO_0000065,None,630.00,Yes
2,None,62275,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,M,UO_0000065,None,43.20,Yes
3,None,68744,[],CHEMBL618322,Cytotoxic activity against 786-0 Renal cancer ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,M,UO_0000065,None,843.00,Yes
4,None,138326,[],CHEMBL619279,Tested for cytotoxicity against 786-0 cell lin...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,Log GI50,None,UO_0000065,None,323.59,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42698,None,24512320,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,uM,UO_0000065,None,490.00,Yes
42699,None,24512321,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,uM,UO_0000065,None,2450.00,IN
42700,None,24512322,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,uM,UO_0000065,None,2260.00,IN
42701,None,24512323,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,uM,UO_0000065,None,2770.00,IN
42702,None,24512324,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5056245,Anticancer activity against human 786-0 cells ...,F,None,None,BAO_0000189,BAO_0000219,...,786-0,9606,None,None,GI50,uM,UO_0000065,None,1490.00,IN

In [ ]:
# considering nM unit for MIC
df = df[(df['Activity'] != 'IN')]
len(df)

517

In [ ]:

df.to_csv('/content/bioactivity_data_786-0_GI50.csv', index=False)